language: node_js
node_js: 7

cache:
  yarn: true
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"

env:
- CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

install:
- yarn

script: echo "Deploying!"

before_deploy: yarn build

deploy:
  provider: firebase
  token:
    secure: "YnFk8oHCXngK1lFvvwXaU0MN8ckW7ASH3/k1lP2UQMUmczi538P8TRwSsVIIshDtero7Y6M1wzETfdMVcdL8AFv91bGMi8LMCJBP8LT2vHnvPe5+zuTvaJgYWUlUrd0++p/y0UQZjK2ynSsNgdABP03kPhTGP0qq48QB/phSJv/tEJbZD2K9TmAfhEpMtwpfjqQ4AXO2sDsF43dgZSWm7u5KyvLzhXl2w1PTLb3DH25xbGvx+6dxFpu/6qu0xHwzZtkv/fGcUyVoja6yJnjoAvYNA3do/Icm/TX5ghPXzD3efTVBy/mTCWzIIIpk83w37lbcMCAbhRDfvXNxDNFi3rTt8FQIwdwW6cqM0yr9IwhhcoI23e0miSen0PgO3JQBsPKw+pUxYoFykF1SuEXbZEo+o988tozvfS/N3FUhsMYqpfq/iucIOPlNJazjFlHLmLHaRLEdK+mED0EScwR4XH0xmSykv2Jc1UEE479kyOLrSdJbExd2vSRuMA1YeNrPNdZ62JWO+cbnQJCoVfXAPFEy50y5tXEygHB8oTW4aJG0ew7lFlLcijPFbg+6cFTPGCayk55MzTekNhwZCOaGOKngN3WAYphrFqvD+HVwmHrcg5ZxMmsKlBvK80lQ5n44ldUaevCjp2tEAIvNkB+J/zlqFP6gjQ2jUvbKeeuVHZc="