language: node_js
os: linux
dist: trusty
sudo: required

node_js:
  - "7"

cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache

before_install:
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn -V

install:
  - yarn

script: npm rebuild node-sass && yarn build

deploy:
  provider: firebase
  token:
    secure: "YnFk8oHCXngK1lFvvwXaU0MN8ckW7ASH3/k1lP2UQMUmczi538P8TRwSsVIIshDtero7Y6M1wzETfdMVcdL8AFv91bGMi8LMCJBP8LT2vHnvPe5+zuTvaJgYWUlUrd0++p/y0UQZjK2ynSsNgdABP03kPhTGP0qq48QB/phSJv/tEJbZD2K9TmAfhEpMtwpfjqQ4AXO2sDsF43dgZSWm7u5KyvLzhXl2w1PTLb3DH25xbGvx+6dxFpu/6qu0xHwzZtkv/fGcUyVoja6yJnjoAvYNA3do/Icm/TX5ghPXzD3efTVBy/mTCWzIIIpk83w37lbcMCAbhRDfvXNxDNFi3rTt8FQIwdwW6cqM0yr9IwhhcoI23e0miSen0PgO3JQBsPKw+pUxYoFykF1SuEXbZEo+o988tozvfS/N3FUhsMYqpfq/iucIOPlNJazjFlHLmLHaRLEdK+mED0EScwR4XH0xmSykv2Jc1UEE479kyOLrSdJbExd2vSRuMA1YeNrPNdZ62JWO+cbnQJCoVfXAPFEy50y5tXEygHB8oTW4aJG0ew7lFlLcijPFbg+6cFTPGCayk55MzTekNhwZCOaGOKngN3WAYphrFqvD+HVwmHrcg5ZxMmsKlBvK80lQ5n44ldUaevCjp2tEAIvNkB+J/zlqFP6gjQ2jUvbKeeuVHZc="
  skip_cleanup: true
